name: cracksense
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - albumentations=1.3.1
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cudatoolkit=11.8.0
  - ffmpeg=5.1.2
  - fftw=3.3.10
  - imageio=2.27.0
  - imageio-ffmpeg=0.4.8
  - imgaug=0.4.0
  - imgviz=1.7.2
  - matplotlib=3.7.1
  - numpy=1.23.5
  - opencv=4.7.0
  - openh264=2.3.1
  - openjpeg=2.4.0
  - openpyxl=3.0.10
  - openssl=3.1.3
  - pillow=9.4.0
  - pip=23.0.1
  - ply=3.11
  - pyqt=5.15.7
  - python=3.10.10
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - scikit-image=0.19.2
  - scikit-learn=1.0.2
  - scipy=1.8.1
  - setuptools=66.0.0
  - shapely=2.0.1
  - sympy=1.11.1
  - tensorboard=2.12.2
  - toml=0.10.2
  - torchaudio=2.0.2
  - torchinfo=1.8.0
  - torchmetrics=0.11.4
  - torchtriton=2.0.0
  - torchvision=0.15.2
  - tqdm=4.65.0
  

